insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Yvon Booley', '1991-11-04', '1928-02-14', 'Morocco', 'Sweden');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ivette Belhome', '1997-06-21', '1944-10-13', 'Indonesia', 'Denmark');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Hermione Burghill', '1992-07-24', '2019-04-09', 'Armenia', 'Portugal');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Morly Randell', '1946-02-02', '2005-10-05', 'France', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sibella Hewins', '1901-04-10', '1919-05-26', 'Iran', 'Dominican Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lilith Caldaro', '2014-04-14', '1948-03-07', 'China', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Megen Jell', '2013-04-01', '2008-10-12', 'Sierra Leone', 'New Zealand');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Steffen Jeanin', '1980-03-08', '1958-08-07', 'Indonesia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Andromache Yegorov', '1976-12-06', '1941-03-12', 'France', 'Mexico');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Tanya Attenbrow', '1931-04-17', '1952-03-09', 'China', 'Bangladesh');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Mandy Middleweek', '1925-05-10', '2007-07-16', 'Indonesia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Marget Goncalo', '1912-05-11', '1991-12-06', 'Indonesia', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Rafa Giacobini', '1967-03-04', '1903-01-24', 'Russia', 'Peru');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Berkie McBean', '2004-11-05', '1989-10-26', 'Indonesia', 'Honduras');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Leeanne Rumford', '1983-11-14', '2002-11-21', 'China', 'Colombia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Glyn Tolputt', '1955-09-23', '1997-10-10', 'Portugal', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Shalna Empringham', '1966-04-10', '1977-05-28', 'China', 'Afghanistan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Tomasine Mennear', '1974-09-07', '1999-04-24', 'Russia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kelcey Fold', '1984-07-05', '2015-05-29', 'Greece', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sasha Kopta', '1903-10-26', '1971-03-09', 'Japan', 'Sweden');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Reiko Culley', '1970-08-03', '2000-07-21', 'Indonesia', 'France');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Reuven Cosslett', '1962-03-07', '1997-11-25', 'Venezuela', 'Armenia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Veda Tregaskis', '1959-03-19', '1932-04-06', 'Indonesia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Davidson Tasker', '1954-08-16', '1986-07-18', 'Indonesia', 'Mongolia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Erl Herety', '1955-04-16', '2022-04-03', 'China', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cairistiona Bambrugh', '1909-04-25', '1974-05-28', 'China', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Rosalie Maevela', '1958-11-30', '2017-05-13', 'United States', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Robinia Ashington', '1991-02-19', '1932-08-26', 'China', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Mercy Brownlie', '1921-01-06', '1952-01-21', 'Indonesia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Theressa Swindle', '1927-08-03', '1916-12-07', 'North Korea', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Carey Plimmer', '1976-01-17', '1963-06-21', 'Russia', 'Bhutan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Giorgio Bagg', '1933-12-15', '2019-05-10', 'China', 'Laos');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bette-ann Beddow', '2018-10-19', '1996-12-22', 'Brazil', 'Central African Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Pepe Lilion', '2020-07-21', '2014-12-10', 'China', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Guglielma O''Growgane', '2022-05-19', '2016-01-07', 'Honduras', 'Morocco');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Pam Gudyer', '1916-11-27', '2013-04-01', 'Indonesia', 'Bangladesh');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Mervin Corragan', '2018-08-17', '1966-01-18', 'Czech Republic', 'Bulgaria');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Shana Parker', '1929-11-04', '1959-02-12', 'Finland', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jeffry Ragsdall', '1997-06-28', '2010-08-13', 'Ukraine', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Gay Mabbs', '2018-06-05', '1901-12-22', 'United States', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Arabel L''Hommee', '1937-08-29', '1977-08-07', 'Guatemala', 'Portugal');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Eloise Garr', '1984-01-15', '1984-07-28', 'Mexico', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Mellisent Streeten', '1917-09-08', '1967-09-22', 'Montenegro', 'Nicaragua');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Zared Pietranek', '1946-07-17', '1972-07-22', 'Japan', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Andromache Tribe', '1941-11-13', '1954-01-09', 'Sweden', 'Madagascar');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jacky Simeoni', '1957-07-06', '1997-01-04', 'China', 'Macedonia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Allister Salery', '1948-12-17', '1986-09-10', 'Canada', 'Egypt');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bettina Dulake', '1964-11-24', '1991-06-20', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ethyl Catto', '1946-06-14', '1996-04-13', 'Russia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Padraig Clotworthy', '1922-11-17', '1925-08-19', 'Indonesia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Maxy Zolini', '2002-09-09', '2013-06-28', 'France', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Suzi Schulze', '1911-10-14', '1968-10-12', 'Indonesia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Averell Hekkert', '2003-02-25', '1950-06-10', 'Croatia', 'Finland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Brena Dewer', '1989-12-02', '1914-02-16', 'Indonesia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Clayton Edworthye', '1977-12-05', '1979-10-22', 'Philippines', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dione Hutcheon', '1958-06-17', '1952-09-24', 'Russia', 'Morocco');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Justin Denver', '1976-12-11', '1912-04-14', 'Iraq', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Pascal Leggs', '2007-12-01', '2002-08-05', 'Brazil', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lucho Heel', '1949-04-13', '2013-08-31', 'Indonesia', 'Nigeria');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Allin Skein', '1910-06-19', '1944-08-05', 'Russia', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jeramie McDuall', '1976-02-03', '2010-09-15', 'Macedonia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cissiee Corssen', '1945-07-05', '1953-08-30', 'Indonesia', 'North Korea');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Elysia Frantz', '1976-06-27', '1969-01-03', 'Russia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Christyna Bickerdike', '1997-12-22', '1964-05-01', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Tamas Gunstone', '1962-05-24', '2000-05-21', 'Bosnia and Herzegovina', 'Germany');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Celine Channing', '1909-01-30', '1967-03-06', 'Ukraine', 'Ukraine');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kele Trulocke', '1908-10-10', '1999-12-18', 'China', 'Estonia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Zaccaria Angerstein', '1986-07-18', '1950-07-11', 'China', 'Sierra Leone');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Geordie Kerans', '1998-06-22', '1947-05-08', 'Russia', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Trenna Ryman', '1971-12-12', '1962-09-05', 'Philippines', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Guy Escalera', '1985-02-05', '1993-10-02', 'Brazil', 'Czech Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Myer Cornner', '1982-10-30', '1934-11-27', 'Indonesia', 'Serbia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Peggy Bicheno', '1948-04-10', '1903-08-28', 'Australia', 'New Zealand');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Winny Drillot', '1972-04-19', '1938-05-19', 'Saudi Arabia', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Robena Youll', '2022-05-18', '1991-02-05', 'France', 'Poland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kellen Tullis', '1963-01-09', '1937-11-14', 'France', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Janine Binnell', '1965-06-14', '1902-08-01', 'Ireland', 'Chile');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cyrillus Beacon', '1911-07-20', '1924-08-10', 'Brazil', 'Peru');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Alfred Skym', '1973-01-11', '1935-01-17', 'Poland', 'Norway');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Hallsy Bradly', '1956-01-30', '1928-07-19', 'China', 'Ethiopia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Renate Sutworth', '1931-04-12', '1947-10-19', 'China', 'Kazakhstan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Madelaine Larby', '1918-02-01', '1957-12-10', 'Russia', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Latia MacKibbon', '1903-06-10', '1911-09-24', 'Uruguay', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Floria McIlvoray', '1947-05-25', '1990-05-07', 'Philippines', 'Armenia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Reagen Haville', '2021-12-16', '1958-07-12', 'Russia', 'Poland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Euell Pughsley', '1952-12-14', '2004-08-18', 'China', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Farlie Gadsden', '1908-02-08', '1928-01-08', 'China', 'Argentina');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Karmen Hedditeh', '1911-04-13', '1980-08-27', 'China', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Hadley Breede', '1979-05-23', '1965-07-17', 'Ukraine', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Keely Sudddard', '1981-09-05', '1909-04-28', 'Czech Republic', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Amandi Murford', '1950-06-01', '1970-09-07', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Salomo Domonkos', '1953-11-10', '1907-02-15', 'Slovenia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Elwin Eble', '1974-10-13', '1984-12-24', 'Indonesia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Fonz Blackshaw', '1906-02-24', '1912-05-12', 'Russia', 'Turkmenistan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lilas MacAvddy', '1950-05-04', '1957-08-31', 'Brazil', 'Thailand');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Chris Stoggell', '1989-06-12', '1990-12-15', 'China', 'Malawi');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Daffi Donnison', '1938-07-08', '1995-03-18', 'Indonesia', 'Hungary');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jonas Fairlie', '1948-04-07', '2019-03-18', 'Philippines', 'Chad');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sonny Adelman', '1985-04-23', '1901-09-13', 'Russia', 'Honduras');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Janine Vials', '1987-10-07', '1906-07-01', 'Guatemala', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Nickolai MacDougall', '1967-08-26', '1900-09-13', 'China', 'Nigeria');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Celia Corking', '1904-05-18', '1942-11-20', 'Palestinian Territory', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Janine Teall', '2022-05-26', '1966-05-31', 'Indonesia', 'Canada');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Tamas Banat', '1973-08-20', '1918-07-19', 'China', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Logan Simcock', '1934-10-06', '1906-05-05', 'Dominican Republic', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kiri Cutler', '1976-05-26', '1942-02-04', 'Pakistan', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Stanwood Sever', '1921-08-12', '1965-07-31', 'Indonesia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Shirline Espadas', '1935-06-12', '1945-11-06', 'Netherlands', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kendell Podbury', '1935-08-14', '1960-02-08', 'Brazil', 'Nigeria');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Conny Norcliff', '1956-12-22', '1949-07-10', 'Thailand', 'Ukraine');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Misha Ballintyne', '1949-10-11', '1936-06-21', 'Russia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dell Tuerena', '1910-10-16', '1937-01-26', 'Guatemala', 'Sudan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Devlen Guidotti', '2013-02-28', '1911-07-18', 'Haiti', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Markos Soots', '1985-11-04', '1938-04-06', 'Russia', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Allsun Chipping', '1949-08-08', '2009-03-01', 'Haiti', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sammy Fahrenbach', '1945-10-10', '1937-12-31', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ursa Feveryear', '1936-06-09', '1935-02-26', 'South Korea', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Denys Massei', '1982-11-27', '1919-10-23', 'Malaysia', 'Mexico');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Garret Saladino', '2006-08-17', '1928-12-27', 'Philippines', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Keslie Beamont', '1995-02-05', '1969-05-03', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Blondy Bortolazzi', '2002-02-12', '1993-06-28', 'Argentina', 'New Caledonia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cathryn Daile', '1992-12-15', '2004-06-07', 'Albania', 'Albania');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Trescha Stoneman', '1997-09-12', '1992-06-11', 'Indonesia', 'Nigeria');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kimmi Sarle', '1923-02-11', '1953-12-06', 'China', 'Mexico');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Zorine Bigmore', '1943-01-11', '1960-05-14', 'Canada', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Nolana Alishoner', '2000-03-23', '1928-10-18', 'Sweden', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sybille Twoohy', '1951-09-08', '1939-08-11', 'Czech Republic', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Pansy Hansom', '1962-11-25', '1992-03-12', 'Spain', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Enos Redbourn', '1986-06-30', '2017-06-22', 'Ethiopia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Valina Sealove', '2015-07-14', '2006-09-18', 'China', 'Tanzania');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bianka Duprey', '1922-08-12', '1971-12-28', 'China', 'Czech Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Christel Towson', '1904-08-06', '1993-04-17', 'Colombia', 'Vietnam');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Nikolaos Climo', '1931-01-08', '1979-01-13', 'China', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Wrennie Hourihan', '1985-03-20', '1944-11-18', 'Sweden', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Blondie Dumphrey', '1948-11-08', '2019-09-16', 'Peru', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Emerson Boost', '1964-06-03', '1930-11-15', 'China', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Mel Crus', '2018-09-23', '1909-10-25', 'Philippines', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lance Dentith', '1991-10-12', '2020-02-05', 'Madagascar', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cissy Dartnall', '1996-04-20', '1944-04-11', 'Philippines', 'Thailand');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Arnaldo Eastope', '1904-09-21', '1942-11-20', 'Vietnam', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lee Dunstall', '1919-08-12', '1954-04-09', 'France', 'Portugal');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dynah Droogan', '1905-01-17', '1994-08-27', 'Philippines', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Christabel Brodest', '1997-07-12', '1901-06-28', 'Russia', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Adair Adney', '1994-08-19', '1941-02-15', 'China', 'Argentina');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jewel Lugard', '1966-10-23', '1954-02-16', 'China', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Talia Huckleby', '1999-06-09', '1993-01-01', 'Serbia', 'Spain');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Benny Stoggles', '1901-07-29', '1947-04-15', 'United Kingdom', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Graig Pollock', '1945-02-25', '1986-10-20', 'Cuba', 'Serbia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Fabien Allflatt', '1997-02-26', '2018-07-28', 'Russia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Stanislaus Tremayle', '1979-04-05', '1907-08-14', 'Indonesia', 'Nicaragua');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Orson Tevelov', '2015-07-08', '2010-09-19', 'Indonesia', 'Germany');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sibylle Canas', '1928-09-15', '1907-08-02', 'Argentina', 'Macedonia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Evyn Craythorn', '1999-12-15', '1994-11-24', 'China', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dannie Mines', '1919-09-30', '2004-04-29', 'Belarus', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Robinett Sizland', '1916-02-11', '1941-11-04', 'Croatia', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cody Saterweyte', '1945-05-26', '1934-08-05', 'Indonesia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Anderea Matlock', '1941-04-06', '2013-08-27', 'Uzbekistan', 'Serbia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Alysa D''eath', '1926-09-03', '1952-12-08', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Erica Tuckie', '1998-04-19', '2013-04-22', 'Russia', 'Iran');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Corenda Dobbing', '2001-06-09', '1905-06-28', 'China', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Conchita Garrit', '2020-09-19', '1940-04-05', 'China', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bryna Palke', '1988-11-25', '1940-07-25', 'Uganda', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Udell Peasegood', '1908-03-01', '1919-11-09', 'Democratic Republic of the Congo', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Mitch Glossup', '1926-05-11', '1949-04-11', 'Indonesia', 'Sweden');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Mal Sowter', '2010-01-06', '2012-07-07', 'China', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jelene Colthard', '1920-01-21', '1947-05-29', 'Indonesia', 'Argentina');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ulla Spolton', '2005-04-22', '1945-07-18', 'Iran', 'France');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jeremiah Tuplin', '2015-08-07', '1973-12-01', 'Indonesia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Georgetta Gorries', '1919-07-12', '2013-07-08', 'China', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Guinevere Curnokk', '2000-06-13', '2009-10-06', 'Philippines', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lindie Porteous', '1926-01-20', '1951-09-04', 'Colombia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Morty Joseland', '1972-07-13', '1985-01-17', 'Indonesia', 'Thailand');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Myrta Tondeur', '1944-12-30', '1985-05-01', 'Philippines', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cristabel Duham', '1908-10-01', '1910-04-29', 'Kenya', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Josselyn Lamey', '1904-04-19', '1943-11-08', 'China', 'Mexico');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Olin Gorton', '1924-03-28', '2008-10-23', 'Indonesia', 'Mexico');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Karylin Ridder', '2013-03-01', '1965-07-06', 'Greece', 'Finland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Rossie Boule', '2003-05-24', '1935-07-22', 'Pakistan', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Blisse Vala', '2003-03-09', '1984-05-16', 'Argentina', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Leyla Zuppa', '1984-10-01', '1919-11-02', 'Mexico', 'Bosnia and Herzegovina');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Doretta Fisk', '1911-01-11', '1913-01-06', 'Trinidad and Tobago', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Cory Jannequin', '1912-05-31', '1956-12-26', 'China', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ethan Kasman', '1965-01-30', '1907-05-25', 'Philippines', 'Spain');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Base Upham', '1927-12-15', '1948-06-05', 'Egypt', 'Sweden');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Annnora Basezzi', '1973-08-10', '1947-08-07', 'Philippines', 'Argentina');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Killian Clamp', '1981-09-10', '2018-07-05', 'Russia', 'Portugal');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Rina Aslen', '2001-03-01', '1964-11-18', 'Bolivia', 'Austria');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Myrta Maiden', '1984-05-19', '1928-10-26', 'Palestinian Territory', 'Sweden');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Marthena Biasotti', '1966-02-13', '1930-01-28', 'Brazil', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Caddric Potapczuk', '1951-10-19', '1925-07-19', 'Czech Republic', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Fletch Esch', '1972-04-15', '1900-08-19', 'Colombia', 'Czech Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Wilhelmina Knobell', '1913-07-08', '1923-09-08', 'Peru', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ode Froment', '1979-07-25', '1972-05-08', 'Poland', 'Serbia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Terry Mattiacci', '2012-11-06', '2000-05-04', 'Indonesia', 'Poland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Derril Mainstone', '1900-05-25', '1940-12-22', 'Indonesia', 'France');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Revkah Antonoyev', '1942-03-04', '1988-11-29', 'Palestinian Territory', 'Latvia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Christos Broodes', '2014-07-19', '1945-07-27', 'Brazil', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Rebecca Boullen', '1920-08-10', '1959-11-18', 'Portugal', 'France');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Matthieu Culmer', '1900-02-02', '1924-02-09', 'Indonesia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jim Hum', '1931-06-01', '1903-06-03', 'Peru', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jeniffer Whitwam', '1987-06-10', '1967-12-22', 'China', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Barclay Fallow', '2011-06-24', '1907-11-26', 'China', 'Chile');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Velma Scibsey', '1948-07-23', '1971-04-17', 'China', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Demeter Disbrow', '1934-10-07', '1980-05-19', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('James Edwin', '1987-12-03', '1924-11-16', 'Philippines', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Grantley Bjorkan', '1953-02-18', '1961-04-27', 'Myanmar', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ezri Bergstram', '1915-04-27', '2000-05-08', 'Venezuela', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Amalle Jowett', '1996-03-31', '1980-09-21', 'China', 'Ukraine');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Francisca Gluyus', '1929-05-08', '2006-11-26', 'Indonesia', 'Sri Lanka');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kimball Hutchins', '1920-02-17', '1919-08-17', 'Afghanistan', 'Argentina');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dorthy Ferrey', '1903-01-08', '1927-03-22', 'Malaysia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lindy Smoth', '1911-01-31', '1999-06-03', 'China', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bernardina Boulding', '1906-06-25', '1917-12-17', 'Netherlands', 'Ethiopia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Nolana Scudamore', '1949-01-04', '1912-08-02', 'Armenia', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Tedra Wedderburn', '1909-07-20', '2007-05-12', 'France', 'Mexico');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Zulema Hallen', '1980-04-01', '2003-04-22', 'Thailand', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Madelene Potte', '1926-09-25', '1960-03-09', 'Indonesia', 'Poland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Galvan Lye', '1936-02-01', '1980-06-20', 'China', 'Ukraine');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Karylin Sollitt', '1983-07-17', '1922-05-03', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Gawain Robers', '1934-09-20', '1951-07-10', 'Russia', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ricard Kerrey', '1924-09-10', '2011-10-06', 'Greece', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Chariot Durdle', '1903-10-06', '1998-03-21', 'Poland', 'Martinique');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jard Surr', '1912-12-27', '1913-02-24', 'Yemen', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Teddi Cass', '1912-05-31', '1901-01-27', 'Philippines', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Denyse Bentall', '1941-11-08', '1951-02-01', 'Brazil', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dickie Gundry', '1956-05-04', '1992-01-26', 'China', 'Panama');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Elie McMinn', '1924-02-11', '1935-01-26', 'Vietnam', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Shantee Vasilechko', '1947-01-17', '1930-05-15', 'Portugal', 'Guatemala');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bel Morfey', '1967-09-04', '1919-09-20', 'Norway', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Hamnet Stonhard', '1999-06-26', '2011-07-04', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Fraze McAleese', '1965-12-20', '1992-01-12', 'Indonesia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Erhard Aindriu', '1940-04-18', '1932-10-26', 'Portugal', 'Portugal');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Felecia Nickels', '1998-11-08', '1946-01-15', 'Netherlands', 'Portugal');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dawna Hauger', '1986-12-19', '1988-06-18', 'China', 'United States');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ferdinanda Tartt', '2008-09-26', '2017-05-26', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Erin Gyrgorcewicx', '1938-03-28', '1928-04-30', 'Indonesia', 'Myanmar');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Christin Lugard', '1941-06-30', '1959-02-23', 'Bangladesh', 'Peru');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Homere Erwin', '1906-02-09', '1916-09-17', 'Russia', 'Czech Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Eolanda Mcimmie', '1928-04-06', '1948-06-05', 'China', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jeane Corrie', '1968-12-21', '2006-01-03', 'American Samoa', 'Poland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Yetta Woofenden', '1934-11-18', '1910-08-06', 'Poland', 'France');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Juliana Bossingham', '1950-05-03', '1917-07-13', 'Brazil', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bud Chrisp', '1969-01-04', '1939-03-02', 'China', 'France');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Binnie Crut', '1937-11-11', '1952-04-30', 'Ukraine', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ezekiel Whitcombe', '2002-01-29', '1918-05-26', 'Poland', 'Czech Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Pryce Emerson', '2004-07-21', '1912-07-09', 'Hungary', 'Republic of the Congo');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Rolph Haddacks', '1994-03-10', '1935-02-24', 'Thailand', 'Cuba');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dorrie Braybrooks', '1927-12-17', '1971-02-15', 'Jordan', 'Iran');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Nels Neil', '2017-04-28', '1920-08-13', 'China', 'Turkmenistan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Elbertine Ferraro', '1968-06-22', '1971-11-05', 'Sudan', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Yance Arboin', '1903-05-30', '2018-10-18', 'Poland', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Thatch Headey', '1960-03-18', '1919-04-19', 'Costa Rica', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sebastian Blankau', '1908-12-09', '2000-02-20', 'China', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Stinky Rewcassell', '2000-12-01', '2010-07-27', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Madelon Tunnicliff', '1950-03-09', '2016-11-17', 'Indonesia', 'Estonia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Tripp McCalum', '2015-03-03', '2014-02-01', 'Yemen', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Brandie Blight', '2007-07-15', '1928-02-10', 'Portugal', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jackie Drakeford', '2012-02-01', '1949-11-04', 'China', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Eli Hairyes', '2011-09-04', '1951-05-10', 'Bulgaria', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Aloise Wallace', '2012-07-24', '1905-09-22', 'Philippines', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sacha Brocklehurst', '1974-06-21', '2009-12-12', 'Kyrgyzstan', 'United Kingdom');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Hamnet Silversmidt', '1972-06-21', '1918-06-18', 'Russia', 'Kenya');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Henryetta Blowen', '2018-05-23', '1967-02-11', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Esteban Shakelady', '1993-04-17', '1995-05-01', 'Indonesia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bobbe Gunderson', '1971-01-15', '2013-09-22', 'Russia', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Ranee Warwicker', '1924-05-02', '1979-09-29', 'Madagascar', 'Niger');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sharona Tilbury', '2011-05-21', '1957-02-28', 'Honduras', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Tabbi Bartosek', '1992-01-30', '1994-07-09', 'Serbia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sabina Dowker', '1901-01-20', '1941-11-02', 'France', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Bathsheba Dumblton', '1962-09-22', '1992-08-16', 'Russia', 'Germany');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Matthias Senett', '1980-04-18', '2010-01-07', 'Colombia', 'Kenya');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Hubie Gleder', '1907-11-05', '1900-01-28', 'Philippines', 'Ireland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Amata Garbott', '1922-09-18', '2009-11-09', 'France', 'Russia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Devondra Stallworth', '1975-03-02', '1900-10-08', 'China', 'Laos');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Lucio Murfin', '1964-02-27', '1900-01-24', 'Portugal', 'Macedonia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Inge Burbage', '1959-06-14', '1945-08-04', 'Philippines', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Saudra Depka', '1946-09-09', '1976-03-01', 'Nigeria', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Darill Antognelli', '1912-11-21', '1978-09-23', 'France', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Gale Jikylls', '1900-02-16', '1981-05-17', 'South Africa', 'Japan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Terra Fenemore', '2013-06-19', '1963-09-12', 'Sweden', 'Sweden');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Selig Lambotin', '1996-07-03', '1980-10-16', 'China', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Dionne Barbie', '1996-02-25', '1995-05-01', 'Mauritius', 'Poland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Araldo Lukock', '1938-01-08', '1944-11-05', 'Poland', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Vicki Ablewhite', '1918-04-29', '1917-05-21', 'Ukraine', 'Ethiopia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Moselle Yakubovics', '1965-04-03', '1915-01-22', 'Nigeria', 'Colombia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Barrie Luigi', '2000-11-20', '1905-07-18', 'China', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Heather Lewnden', '1950-07-28', '1929-06-21', 'Brazil', 'Brazil');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Carmelita Branson', '1968-09-13', '2008-02-04', 'China', 'Oman');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Gaven Huleatt', '1917-06-27', '2005-09-03', 'Russia', 'Czech Republic');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Glad Datte', '1916-10-02', '1923-06-07', 'Russia', 'Mexico');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Zora Mayze', '1997-11-18', '1911-04-12', 'South Africa', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Michale Dongles', '1901-02-10', '1993-04-25', 'United States', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Jerrylee Earngy', '1923-01-20', '1978-02-12', 'Poland', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Langsdon Brewer', '1936-03-13', '2008-11-11', 'Poland', 'Poland');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Melisande Wraight', '1965-02-11', '1949-03-25', 'Indonesia', 'Philippines');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Maria Twinborne', '2001-11-25', '1952-06-06', 'France', 'Afghanistan');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Felicity Rudeyeard', '2014-08-11', '2016-10-04', 'Indonesia', 'China');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Kirsteni Simmins', '1997-07-08', '2020-04-15', 'Thailand', 'Canada');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('Sabra Ponten', '1999-09-19', '2020-08-14', 'Indonesia', 'Indonesia');
insert into artist (aname, date_of_birth, date_of_death, place_of_birth, place_of_death) values ('George Niesel', '1932-11-10', '1998-03-30', 'Bolivia', 'Russia');
